### PR TITLE
多多

### PR DESCRIPTION
**Pull request by HDsee**
http://35.78.45.29:3000/
http://35.78.45.29:3000/attraction/10

### CODE REVIEW

**Comment by cwpeng** [comment]
Input border style should align with design.

**Comment by HDsee** [comment]
I have modified.
please, check again.

**Comment by cwpeng** [comment]
Cannot connect to your server.

**Comment by HDsee** [comment]
Sorry sir!
The server has been restarted now.
Please check it.

**Comment by cwpeng** [comment]
Set border width to 1px.

**Comment by HDsee** [comment]
OK sir !

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
