### PR TITLE
多多

### PR DESCRIPTION
**Pull request by HDsee**
http://35.78.45.29:3000/api/attraction/1
http://35.78.45.29:3000/api/attractions?page=0&keyword=溫泉
http://35.78.45.29:3000/api/attractions?page=1

### CODE REVIEW

**Comment by cwpeng** [comment]
Your URLs are broken. Fix them and leave message for me to review again.

**Comment by HDsee** [comment]
可以了 麻煩老師再試一次

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. "nextPage" of http://35.78.45.29:3000/api/attractions?page=3 should be 4.
2. "images" of http://35.78.45.29:3000/api/attractions?page=3 should be an array containing image URLs separately, not a string.

Fix issues, create new commits, and ask me to review again from right side of this page.

**Comment by HDsee** [comment]
please re

**Pull request closed without merging**
